# Generated by Django 5.1.7 on 2025-04-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_notification_link_notification_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("join_request", "Join Request"),
                    ("status_update", "Status Update"),
                ],
                default="join_request",
                max_length=20,
            ),
        ),
    ]
