# Generated by Django 5.1.7 on 2025-04-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
